services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FIRECRAWL_PORT:-3006}:${FIRECRAWL_PORT:-3006}"
    env_file:
      - .env
    restart: unless-stopped
